services:
  pg:
    image: postgres:16-alpine
    ports:
      - "7000:5432"
    environment:
        POSTGRES_USER: docker
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: base
    volumes:
      - pg-data:/var/lib/postgresql/pg-data
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ports:
      - "6379:6379"
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data
    command: ["--proactor_threads=4"]

volumes:
   pg-data:
   dragonflydata: